# Generated by Django 4.2 on 2025-02-07 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendtime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50, verbose_name='主な内容')),
                ('contents', models.TextField(verbose_name='内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='connectimage', verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='イベント名')),
                ('live_name', models.CharField(max_length=255, verbose_name='ライブ名')),
                ('live_time', models.DateTimeField(blank=True, null=True, verbose_name='日付')),
                ('open_time', models.DateTimeField(verbose_name='開場時間')),
                ('event_time', models.DateTimeField(verbose_name='イベント時間')),
                ('price', models.IntegerField(verbose_name='料金')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='チケット枚数')),
                ('remaining_tickets', models.PositiveIntegerField(default=0, verbose_name='残りチケット枚数')),
                ('resale_tickets', models.PositiveIntegerField(default=0, verbose_name='再販チケット枚数')),
                ('total_sold_tickets', models.IntegerField(default=0, verbose_name='購入済みのチケット枚数')),
                ('limit', models.TextField(blank=True, null=True, verbose_name='申し込み制限')),
                ('payment', models.TextField(choices=[('cash', 'コンビニ支払い'), ('credit_card', 'クレジットカード'), ('QR payment', 'QR決済')], verbose_name='支払い方法')),
                ('period', models.DateTimeField(verbose_name='販売終了日')),
                ('winning', models.DateTimeField(verbose_name='当落発表日')),
                ('payment_fin', models.DateTimeField(verbose_name='お支払い期限')),
                ('attention', models.TextField(blank=True, null=True, verbose_name='注意事項')),
                ('category', models.CharField(choices=[('detail', '会場見え方'), ('ticket', '飲食'), ('stage', '交通情報')], default='detail', max_length=50, verbose_name='カテゴリ')),
                ('comment', models.TextField(blank=True, verbose_name='イベント詳細情報')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/posts/', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_title', models.CharField(max_length=255, verbose_name='イベント名')),
                ('re_price', models.IntegerField(verbose_name='料金')),
                ('re_image', models.ImageField(blank=True, null=True, upload_to='uploads/posts/', verbose_name='画像')),
                ('re_remaining_tickets', models.PositiveIntegerField(default=0, verbose_name='残りチケット枚数')),
                ('re_resale_tickets', models.PositiveIntegerField(default=0, verbose_name='再販チケット枚数')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='会場名')),
                ('address', models.TextField(verbose_name='住所')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話番号')),
                ('floor_map', models.ImageField(blank=True, null=True, upload_to='uploads/venues/', verbose_name='フロアマップ')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='収容人数')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='追加情報')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generate_iframe', models.TextField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_images/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ticket_app.venue')),
            ],
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '結果待ち'), ('won', '当選'), ('lost', '落選'), ('canceled', 'キャンセル')], default='pending', max_length=50, verbose_name='申し込みステータス')),
                ('is_resale', models.BooleanField(default=False)),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='申し込み日時')),
                ('result_date', models.DateTimeField(verbose_name='当選発表日')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('reason', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='ticket_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='購入枚数')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='キャンセル済み')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='購入日')),
                ('event_date', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('seat_row', models.CharField(max_length=10)),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('pending', '保留'), ('paid', '支払い済み')], default='pending', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.post', verbose_name='関連イベント')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='購入者')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_app.venue', verbose_name='会場'),
        ),
        migrations.CreateModel(
            name='Connectreply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendtime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=50, verbose_name='主な内容')),
                ('contents', models.TextField(default='', verbose_name='内容')),
                ('image', models.ImageField(blank=True, default='', upload_to='connectimage', verbose_name='画像')),
                ('connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ticket_app.connect')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('seat_view', '座席からの見え方'), ('event', 'イベント'), ('transport', '交通情報')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ticket_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
